Update solver to 4.6
redhat-gpte-devopsautomation/FTL pull request #31
Opened 2021-01-23 17:54 UTC by gmontalvoy

- Moved from openssl to cfssl 
- Modified bootstrap-ignition to ignitionV3
- Changed {{ ocp_version }} and {{ rhcos_image_version }}
- Added ca and ca-server files
- Moved from domain.crt to ca.pem 
- Updated ubi to 8.3
- Updated python script to create master ignition files.

2021-01-25 06:28 UTC, newgoliath requested changes
needs fix to master.ign script, based on docs.  Failing my install.

2021-01-25 06:32 UTC, newgoliath commented
> needs fix to master.ign script, based on docs. Failing my install.

Wait, why can't I delete this comment.. I was wrong.  You did it already.

2021-01-25 13:57 UTC, gmontalvoy commented
As discussed, closed by mistake

2021-01-28 20:46 UTC, wkulhanek approved these changes

2021-01-28 20:46 UTC, merged